version: '3.3'
services: 
    web:
        build: .
        image: appsec:latest
        ports: 
            - "8080:8080"
        volumes:
            - .:/app
        deploy:
            replicas: 4   
            resources:
                limits:
                    cpus: '0.3'
                    memory: '100M'
                reservations:
                    cpus: '0.2'
                    memory: '360M'
        environment:
            expose:
                -"8080"
secrets:
    first_secret: 
        file: ./adminpass.txt